### ISSUE TITLE
Failed to show the Call Sid 

### ISSUE THREAD

**Issue by beckondelve1** [twilio/twilio-client-quickstart-android#7]
I am using this android sdk for twilio calls. Everything works fine . But **in case of an outgoing call when the onConnected() method gets fired  , it does not gives the call sid.**

```
@Override
    public void onConnected(Connection eer) {
        Log.e(TAG, "onConnected");

       String sid = connection.getParameters()
                        .get(Connection.IncomingParameterCallSIDKey); 
             Log.e("call_sid", sid + "on connected"); // this comes null 
}

```
over here .. the connection parameter gives the sid as null..

**Comment by tmconnors** [comment]
@beckondelve1 This issue has been fixed in the 1.2.13. You can download the SDK from here: https://www.twilio.com/docs/api/client/android

**Comment by beckondelve1** [comment]
hello tmconnors.. i have checked the new sdk also.. but the issue is still there.. please verify it once again .. as i checked the issue more than 3 times... 
i request you to solve it properly ..

**Comment by tmconnors** [comment]
Hello @beckondelve1. Verified the CallSID exists both for incoming and outgoing during Client-Client and Client-PSTN calls using 1.2.13. Tested using the mobile-quickstart and client-quickstart. Please verify you're using the expected SDK Version by adding:

`Log.e(TAG, "Twilio SDK Version: Twilio.getVersion()` to the quickstart. 

Perhaps a clean build will help. If you're using AS I'd invalidate your caches and restart too.

If you're using Eclipse (and consequently the uncombined jar version) have you updated the shared libraries as well?
